### PR TITLE
Original setup

### LINKED ISSUE #139: Makefile step to build protobuf

### PR DESCRIPTION
**Pull request by ErinHales**
Closes #139

### CODE REVIEW

**Comment by prestwich** [comment]
build is erroring because we need to set `GO111MOUDLE=auto` instead of `=on`

https://github.com/golang/go/issues/31997#issuecomment-491931353

**Comment by ewilz** [comment]
I think you need to change it here too! https://github.com/summa-tx/relays/blob/erinhales/protobuf-build/.travis.yml#L6

**Comment by ewilz** [comment]
I changed the `.travis.yml` to auto and got _further_ in the build?? Not sure if that's helpful or not: https://travis-ci.com/github/summa-tx/relays/jobs/488309150

**Comment by ErinHales** [comment]
> I changed the `.travis.yml` to auto and got _further_ in the build?? Not sure if that's helpful or not: https://travis-ci.com/github/summa-tx/relays/jobs/488309150

Interesting.  That's not what I was getting.  I met with James this morning and we decided we are actually going to nuke this Makefile.  It's much larger and more complex than what we need.

**Pull request merged**
