### PR TITLE
Height/verified bkd lca

### LINKED ISSUE #80: Show height for best known digest and updatedAt
See Current Block section for how height works

Updated At should be a time stamp. Will need to filter this for display.

### LINKED ISSUE #81: Show height for lca and updatedAt
See Current Block section for how height works

Updated At should be a time stamp. Will need to filter this for display.

Related to #80

### PR DESCRIPTION
**Pull request by ErinHales**
Closes #80 
Closes #81 

 - Splits `relay` in state into `bkd` and `lca` objects.
 - Updates some `convertEndian` logic, renames it to `reverseEndianness`.  This is for my own sanity since this is what this function is called in our other projects.
 - Fixes `Display-Mins`.  Somewhere `timestamp` is getting passed in as a string instead of as a date.  My guess is that this has something to do with how we're storing it in local storage. `Display-Mins` now accepts strings and dates.

### CODE REVIEW

**Comment by ErinHales** [comment]
@barbaraliau  My main concern with this is that the relay is returning a height of 0 for BKD and LCA which doesn't seem right...  And I don't know of another way to get or calculate height.  Any suggestions?

**Comment by barbaraliau** [comment]
@ErinHales hmm...I'll look at it. Do your relay logs show a height?

**Comment by ErinHales** [comment]
@barbaraliau I'm working with James right now to see if we can figure it out.  I think this is something we need to fix in the relay

**Comment by barbaraliau** [comment]
Ok sounds good.

**Pull request merged**
